### ISSUE TITLE
Multi-line banner example

### ISSUE THREAD

**Issue by gpn005** [aruba/aoscx-ansible-role#12]
Would it be possible to show how to do a multi-line banner in your documentation? I don't see any details explaining how this module may understand line breaks. Most customers have a long legal disclaimer for their banner which is more than 1 line so I think this would be of great benefit to the community.

**Comment by tchiapuziowong** [comment]
Hi @gpn005 !!

I've updated the module documentation to reflect a multi-line banner example : https://github.com/aruba/aoscx-ansible-role/commit/1e288703f71648a7109c5285be8092852f6ddcb1

When it comes to multi-line string objects in Ansible this stackoverflow post has other methods of implementing this as well: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines

**Comment by gpn005** [comment]
Thank you! I am not a programmer so all the details around a lot of this stuff is over my head so examples help.

Thanks,

-Geoff

Upcoming PTO:
July 20th-26th
August 24th-30th

Geoff Novak
Sr. Network Engineer
Sirius Computer Solutions
c | (610) 742-7109  o | (215) 695-5112
Geoffrey.Novak@siriuscom.com<mailto:Geoffrey.Novak@siriuscom.com>
[ccnp_routingswitching_sm]
