### ISSUE TITLE
Running the first aoscx playbook

### ISSUE THREAD

**Issue by DungKHoang** [aruba/aoscx-ansible-role#14]
My ansible version is 2.9.1
I install aoscx ansible in an Ansible tower machine using the instructions in the readme file
I verify that the role is in /etc/ansible/.roles
I create an inventory file and try to run the aoscx_facts example
and get the following error:

PLAY [all] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [aoscx_1]

TASK [Execute show run on the switch] ************************************************************************************************************************************************************************
fatal: [aoscx_1]: FAILED! => {"msg": "Could not find imported module support code for aoscx.  Looked for either to_list.py or utils.py"}

PLAY RECAP ***************************************************************************************************************************************************************************************************
aoscx_1                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Any idea on how to fix this basic issue?
Thanks!

**Comment by tchiapuziowong** [comment]
Hello!

This could be due to a missing dependency with the netcommon collection - could you execute this command to ensure it's installed and try to run the playbook again:
`ansible-galaxy collection install ansible.netcommon -f`

**Comment by DungKHoang** [comment]
Beautiful! It works.
Thanks so much
