### ISSUE TITLE
unterminated character set at position 0 when trying to use aoscx_command

### ISSUE THREAD

**Issue by amworden** [aruba/aoscx-ansible-role#15]
Anytime I try to run the aoscx command I get the following error:
FAILED! => {"changed": false, "msg": "unterminated character set at position 0"}

ansible 2.10.8
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:13:35) [Clang 11.0.0 (clang-1100.0.33.17)]

**Comment by amworden** [comment]
More info:
The full traceback is:
  File "/var/folders/54/vd26_dld6hdfplq92g3jm54c0000gq/T/ansible_aoscx_command_payload_fkrbuhsb/ansible_aoscx_command_payload.zip/ansible/module_utils/aoscx.py", line 397, in run_commands
    return conn.run_commands(commands=commands, check_rc=check_rc)
  File "/var/folders/54/vd26_dld6hdfplq92g3jm54c0000gq/T/ansible_aoscx_command_payload_fkrbuhsb/ansible_aoscx_command_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [DEVICE NAME]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show run"
            ],
            "interval": 1,
            "match": "all",
            "output_file": null,
            "output_file_format": "json",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "unterminated character set at position 0"
}

**Comment by tchiapuziowong** [comment]
Hi @adammworden ! Thank you for this information! What switch platform/firmware are you experiencing this with? Are you able to run any other module successfully? such as `aoscx_config` or even one that uses REST API like `aoscx_vlan`?
