### ISSUE TITLE
Not working check mode

### ISSUE THREAD

**Issue by rhizoet** [aruba/aoscx-ansible-role#20]
We use this role together with Gitlab CI/CD to automate our switches.
Therefore it is essential that we can use the check mode in the pipeline.

With `ansible-playbook playbook.yml --check` everything is shown in green (ok), so there are no changes. However, I definitely have a diff on the switches and in the playbook.

As connection I use the aoscx method. It looks to me that in check mode no connection is made to the switches and the modules are only tested locally to see if it fits (sort of linting).

Have I overlooked something in the documentation or do I have to set something else so that the check mode works correctly?

**Comment by tchiapuziowong** [comment]
Hi @rhizoet ! Thank you for bringing this to our attention - at this time we're only supporting the AOS-CX Collection for bug fixes, enhancements, and new modules - I've opened up an issue within the collection repo to track this - https://github.com/aruba/aoscx-ansible-collection/issues/25
